### ISSUE TITLE
[Frontend] Offline meeting

### ISSUE THREAD

**Issue by likelionWonHo** [kosslab-kr/gitCodeShare.com#49]
### Front end Team Meeting

![kakaotalk_photo_2018-08-24-21-22-24](https://user-images.githubusercontent.com/18139217/44584407-cd628200-a7e3-11e8-9ba3-540c28daf03e.jpeg)

#### Today we did
 - Analyzed project default structure
 - Studied about AntDesign
 - Defined component and pages we need
 	1. Conpoment
		- Use antdesign default(Layout, Header, Footer, Menus, Card, Modal ...etc)
		- Contributor thumbnail
		- Code editor
		- Login modal (page ? or modal)
	2. Page
		- index
		- contributors
		- feature
		- code view page

#### Planning to next offline meeting
  - Basic Markup and styling
  - Code will merge on [this repo](https://github.com/likelionWonHo/gitCodeShare.com).
  - [Study about mobx elements and API](https://mobx.js.org/refguide/object.html)

#### Question
 1. We need clear standard about stylsheet file division. For example, We are considering that make each stylesheet file for each component or define style by styled-component in component > [component].js file. which is right? is there more efficient way or any standard? Could we define our own standard?
 2. Please confirm for components and pages we divided. @thomasJang @gimdongwoo

**Comment by thomasJang** [comment]
You can use it in gitShare projects For styling 'less', 'scss', 'styled-component'.
However, I think that it is better to use only 'styled-component' when dealing with the style of 'react components'.

Here's how to use 'styled' inside a component.

I recommended that you create and use the 'styledComponents' folder for convenient use of 'styled-components'
.
**styledComponents/index.ts**
```js
export { default as styled, ThemeProvider, withTheme } from 'styled-components';
export { default as theme } from './theme';
export { RoundedButton } from './StyledButton';
```
If you do this, you can simply import 'styledComponents' from 'component'.

**components/Sample.tsx**
```js
import * as React from 'react';
import { styled, RoundedButton } from '../styledComponents';

interface IProps {}

const Component = styled.div`
  margin: 50px;

  [data-title] {
    font-size: 20px;
    color: ${props => props.theme.textColor};
  }
  [data-item] {
    border: 1px solid #000;
  }
`;

class Sample extends React.Component<IProps> {
  render() {
    return (
      <Component>
        <div data-title>I am Title</div>
        <div data-item>Item</div>
        <div data-item>Item</div>
        <RoundedButton>Button</RoundedButton>
      </Component>
    );
  }
}

export default Sample;
```

Here is a description of the restyling component.

**styledComponents/Button.tsx**
```js
import styled from 'styled-components';
import { Button } from 'antd';

const RoundedButton: typeof Button = styled(Button as any)`
  &.ant-btn {
    border-radius: 30px;
  }
` as any;

export { RoundedButton };
```
In this case, it is better to use it mainly for styling a component that has already been created. Because you can style in the new component.

---- 

and I make some folder(components, styledComponents) and has pushed to our repository

**Comment by thomasJang** [comment]
and I also recommend using https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components for autocomplete in VSCode.
